#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
  DROP SCHEMA IF EXISTS testing CASCADE;
  CREATE SCHEMA testing;
  CREATE TABLE IF NOT EXISTS testing.users (
    id          BIGSERIAL PRIMARY KEY,
    email       VARCHAR(200) NOT NULL,
    first_name  VARCHAR(200) NOT NULL,
    last_name   VARCHAR(200) NOT NULL,
    username    VARCHAR(50) UNIQUE NOT NULL,
    UNIQUE (username)
  );
  COMMIT;
EOSQL
# psql -f ./schema.sql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"